version: '3'
services:
  voice-recognize-app:
    hostname: voice-recognize-app-server
    build: ./voice-recognize
    volumes:
      - ./voice-recognize:/app
      - socket:/tmp
    container_name: 'voice-recognize-app-server'
    ports:
      - '5000:5000'
    networks:
      - flask-app-network
    command: uwsgi --ini /app/uwsgi.ini

  dialogue-generation:
    hostname: dialogue-generation-app-server
    build: ./dialogue-generation
    volumes:
      - ./dialogue-generation:/app
      - socket:/tmp
    container_name: 'dialogue-generation-app-server'
    ports:
      - '5001:5001'
    networks:
      - flask-app-network
    command: uwsgi --ini /app/uwsgi.ini

  web:
    image: nginx:latest
    ports:
      - "80:80"
    container_name: 'app-nginx'
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - socket:/tmp
    networks:
      - flask-app-network

networks:
  flask-app-network:
    driver: bridge

volumes:
  socket:
  db_volume:
