apiVersion: v1
kind: Service
metadata:
  name: dialogue-generation-app-server
  labels:
    app: dialogue-generation-app-server
spec:
  type: ClusterIP
  ports:
    - name: http-port
      protocol: TCP
      port: 5001
      targetPort: 5001
  selector:
    app: dialogue-generation-app-server
