name: Linter

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }} # Python環境のセットアップ
      uses: actions/setup-python@v4 # Python環境のセットアップアクションを使用
      with:
          python-version: ${{ matrix.python-version }} # マトリクスで指定されたPythonバージョンを使用
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 reviewdog
        
    - name: Run flake8 with reviewdog
      run: |
        flake8 voice-recognize dialogue-generation --show-source > flake8_output.txt || true
        reviewdog -f=flake8 -name="flake8" -reporter=github-pr-check -level=error < flake8_output.txt
