name: Linter

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }} # Python環境のセットアップ
    
    - uses: actions/setup-python@v4 # Python環境のセットアップアクションを使用
      with:
          python-version: ${{ matrix.python-version }} # マトリクスで指定されたPythonバージョンを使用
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        
    - name: Run flake8 with reviewdog
      uses: reviewdog/action-flake8@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        level: error
        reporter: github-pr-check
        fail_on_error: true
        path: "voice-recognize dialogue-generation"
