apiVersion: apps/v1
kind: Deployment
metadata:
  name: voice-recognize-app-server
spec:
  selector:
    matchLabels:
      app: voice-recognize-app-server
  replicas: 1
  template:
    metadata:
      labels:
        app: voice-recognize-app-server
    spec:
      containers:
        - name: voice-recognize-app-server
          image: asia-northeast1-docker.pkg.dev/gcp-compute-engine-343613/ar-app-backend/voice-recognize-app-server:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
