apiVersion: v1
kind: Service
metadata:
  name: voice-recognize-app-server
  labels:
    app: voice-recognize-app-server
spec:
  type: ClusterIP
  ports:
    - name: http-port
      protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: voice-recognize-app-server
