apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-nginx
spec:
  selector:
    matchLabels:
      app: app-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: app-nginx
    spec:
      containers:
        - name: app-nginx
          image: asia-northeast1-docker.pkg.dev/gcp-compute-engine-343613/ar-app-backend/app-nginx:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
